# Generated by Django 4.1 on 2022-08-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="titre")),
                (
                    "comment",
                    models.CharField(max_length=6000, verbose_name="commentaire"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="titre")),
                (
                    "description",
                    models.CharField(max_length=6000, verbose_name="description"),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="image")),
            ],
        ),
    ]
