# Generated by Django 4.1 on 2022-08-19 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.ticket",
            ),
        ),
    ]
