# Generated by Django 4.1 on 2022-08-21 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_ticket_review_review_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="id",
        ),
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="myapp.ticket",
            ),
            preserve_default=False,
        ),
    ]
