# Generated by Django 4.1 on 2022-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_review_id_alter_review_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
