# Generated by Django 4.1 on 2022-08-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_review_date_created_ticket_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(verbose_name="commentaire"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
    ]
